/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.horizon.JSON;

/**
 * An allowed parameter value for an OpenFigi Parameter Option.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AllowedParameterValue {
  public static final String SERIALIZED_NAME_ALLOWED_VALUE = "allowedValue";
  @SerializedName(SERIALIZED_NAME_ALLOWED_VALUE)
  private String allowedValue;

  public AllowedParameterValue() {
  }

  public AllowedParameterValue allowedValue(String allowedValue) {
    
    this.allowedValue = allowedValue;
    return this;
  }

   /**
   * 
   * @return allowedValue
  **/
  @jakarta.annotation.Nonnull
  public String getAllowedValue() {
    return allowedValue;
  }


  public void setAllowedValue(String allowedValue) {
    this.allowedValue = allowedValue;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllowedParameterValue allowedParameterValue = (AllowedParameterValue) o;
    return Objects.equals(this.allowedValue, allowedParameterValue.allowedValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowedValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllowedParameterValue {\n");
    sb.append("    allowedValue: ").append(toIndentedString(allowedValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("allowedValue");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("allowedValue");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AllowedParameterValue
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AllowedParameterValue.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AllowedParameterValue is not found in the empty JSON string", AllowedParameterValue.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AllowedParameterValue.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("allowedValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `allowedValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("allowedValue").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AllowedParameterValue.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AllowedParameterValue' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AllowedParameterValue> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AllowedParameterValue.class));

       return (TypeAdapter<T>) new TypeAdapter<AllowedParameterValue>() {
           @Override
           public void write(JsonWriter out, AllowedParameterValue value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AllowedParameterValue read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AllowedParameterValue given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AllowedParameterValue
  * @throws IOException if the JSON string is invalid with respect to AllowedParameterValue
  */
  public static AllowedParameterValue fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AllowedParameterValue.class);
  }

 /**
  * Convert an instance of AllowedParameterValue to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
