/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.horizon.JSON;

/**
 * Request to create a new draft versioned configuration.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateVersionedConfigurationDraftRequest {
  public static final String SERIALIZED_NAME_MAJOR_VERSION = "majorVersion";
  @SerializedName(SERIALIZED_NAME_MAJOR_VERSION)
  private Integer majorVersion;

  public static final String SERIALIZED_NAME_MINOR_VERSION = "minorVersion";
  @SerializedName(SERIALIZED_NAME_MINOR_VERSION)
  private Integer minorVersion;

  public static final String SERIALIZED_NAME_SOURCE_MAJOR_VERSION = "sourceMajorVersion";
  @SerializedName(SERIALIZED_NAME_SOURCE_MAJOR_VERSION)
  private Integer sourceMajorVersion;

  public static final String SERIALIZED_NAME_SOURCE_MINOR_VERSION = "sourceMinorVersion";
  @SerializedName(SERIALIZED_NAME_SOURCE_MINOR_VERSION)
  private Integer sourceMinorVersion;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;

  public CreateVersionedConfigurationDraftRequest() {
  }

  public CreateVersionedConfigurationDraftRequest majorVersion(Integer majorVersion) {
    
    this.majorVersion = majorVersion;
    return this;
  }

   /**
   * The major version for the new draft. Must be supplied together with minorVersion, or both omitted to auto-assign the next version.
   * @return majorVersion
  **/
  @jakarta.annotation.Nullable
  public Integer getMajorVersion() {
    return majorVersion;
  }


  public void setMajorVersion(Integer majorVersion) {
    this.majorVersion = majorVersion;
  }


  public CreateVersionedConfigurationDraftRequest minorVersion(Integer minorVersion) {
    
    this.minorVersion = minorVersion;
    return this;
  }

   /**
   * The minor version for the new draft. Must be supplied together with MajorVersion, or both omitted to auto-assign the next version.
   * @return minorVersion
  **/
  @jakarta.annotation.Nullable
  public Integer getMinorVersion() {
    return minorVersion;
  }


  public void setMinorVersion(Integer minorVersion) {
    this.minorVersion = minorVersion;
  }


  public CreateVersionedConfigurationDraftRequest sourceMajorVersion(Integer sourceMajorVersion) {
    
    this.sourceMajorVersion = sourceMajorVersion;
    return this;
  }

   /**
   * The major version of an existing record to copy the value from. Must be supplied together with SourceMinorVersion. If omitted, the new draft is initialised with an empty JSON object.
   * @return sourceMajorVersion
  **/
  @jakarta.annotation.Nullable
  public Integer getSourceMajorVersion() {
    return sourceMajorVersion;
  }


  public void setSourceMajorVersion(Integer sourceMajorVersion) {
    this.sourceMajorVersion = sourceMajorVersion;
  }


  public CreateVersionedConfigurationDraftRequest sourceMinorVersion(Integer sourceMinorVersion) {
    
    this.sourceMinorVersion = sourceMinorVersion;
    return this;
  }

   /**
   * The minor version of an existing record to copy the value from. Must be supplied together with SourceMajorVersion. If omitted, the new draft is initialised with an empty JSON object.
   * @return sourceMinorVersion
  **/
  @jakarta.annotation.Nullable
  public Integer getSourceMinorVersion() {
    return sourceMinorVersion;
  }


  public void setSourceMinorVersion(Integer sourceMinorVersion) {
    this.sourceMinorVersion = sourceMinorVersion;
  }


  public CreateVersionedConfigurationDraftRequest value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * The initial JSON value for the new draft. If omitted, the draft is initialised with an empty JSON object. Cannot be supplied together with SourceMajorVersion/SourceMinorVersion.
   * @return value
  **/
  @jakarta.annotation.Nullable
  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateVersionedConfigurationDraftRequest createVersionedConfigurationDraftRequest = (CreateVersionedConfigurationDraftRequest) o;
    return Objects.equals(this.majorVersion, createVersionedConfigurationDraftRequest.majorVersion) &&
        Objects.equals(this.minorVersion, createVersionedConfigurationDraftRequest.minorVersion) &&
        Objects.equals(this.sourceMajorVersion, createVersionedConfigurationDraftRequest.sourceMajorVersion) &&
        Objects.equals(this.sourceMinorVersion, createVersionedConfigurationDraftRequest.sourceMinorVersion) &&
        Objects.equals(this.value, createVersionedConfigurationDraftRequest.value);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(majorVersion, minorVersion, sourceMajorVersion, sourceMinorVersion, value);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateVersionedConfigurationDraftRequest {\n");
    sb.append("    majorVersion: ").append(toIndentedString(majorVersion)).append("\n");
    sb.append("    minorVersion: ").append(toIndentedString(minorVersion)).append("\n");
    sb.append("    sourceMajorVersion: ").append(toIndentedString(sourceMajorVersion)).append("\n");
    sb.append("    sourceMinorVersion: ").append(toIndentedString(sourceMinorVersion)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("majorVersion");
    openapiFields.add("minorVersion");
    openapiFields.add("sourceMajorVersion");
    openapiFields.add("sourceMinorVersion");
    openapiFields.add("value");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CreateVersionedConfigurationDraftRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateVersionedConfigurationDraftRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateVersionedConfigurationDraftRequest is not found in the empty JSON string", CreateVersionedConfigurationDraftRequest.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateVersionedConfigurationDraftRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateVersionedConfigurationDraftRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateVersionedConfigurationDraftRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateVersionedConfigurationDraftRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateVersionedConfigurationDraftRequest>() {
           @Override
           public void write(JsonWriter out, CreateVersionedConfigurationDraftRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateVersionedConfigurationDraftRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CreateVersionedConfigurationDraftRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CreateVersionedConfigurationDraftRequest
  * @throws IOException if the JSON string is invalid with respect to CreateVersionedConfigurationDraftRequest
  */
  public static CreateVersionedConfigurationDraftRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateVersionedConfigurationDraftRequest.class);
  }

 /**
  * Convert an instance of CreateVersionedConfigurationDraftRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
