/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.horizon.JSON;

/**
 * Override values for property Display Name and Description
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LusidPropertyDefinitionOverrides {
  public static final String SERIALIZED_NAME_DISPLAY_NAME_OVERRIDE = "displayNameOverride";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME_OVERRIDE)
  private String displayNameOverride;

  public static final String SERIALIZED_NAME_DESCRIPTION_OVERRIDE = "descriptionOverride";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_OVERRIDE)
  private String descriptionOverride;

  public LusidPropertyDefinitionOverrides() {
  }

  public LusidPropertyDefinitionOverrides displayNameOverride(String displayNameOverride) {
    
    this.displayNameOverride = displayNameOverride;
    return this;
  }

   /**
   * 
   * @return displayNameOverride
  **/
  @jakarta.annotation.Nullable
  public String getDisplayNameOverride() {
    return displayNameOverride;
  }


  public void setDisplayNameOverride(String displayNameOverride) {
    this.displayNameOverride = displayNameOverride;
  }


  public LusidPropertyDefinitionOverrides descriptionOverride(String descriptionOverride) {
    
    this.descriptionOverride = descriptionOverride;
    return this;
  }

   /**
   * 
   * @return descriptionOverride
  **/
  @jakarta.annotation.Nullable
  public String getDescriptionOverride() {
    return descriptionOverride;
  }


  public void setDescriptionOverride(String descriptionOverride) {
    this.descriptionOverride = descriptionOverride;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LusidPropertyDefinitionOverrides lusidPropertyDefinitionOverrides = (LusidPropertyDefinitionOverrides) o;
    return Objects.equals(this.displayNameOverride, lusidPropertyDefinitionOverrides.displayNameOverride) &&
        Objects.equals(this.descriptionOverride, lusidPropertyDefinitionOverrides.descriptionOverride);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayNameOverride, descriptionOverride);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LusidPropertyDefinitionOverrides {\n");
    sb.append("    displayNameOverride: ").append(toIndentedString(displayNameOverride)).append("\n");
    sb.append("    descriptionOverride: ").append(toIndentedString(descriptionOverride)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("displayNameOverride");
    openapiFields.add("descriptionOverride");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to LusidPropertyDefinitionOverrides
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!LusidPropertyDefinitionOverrides.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LusidPropertyDefinitionOverrides is not found in the empty JSON string", LusidPropertyDefinitionOverrides.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("displayNameOverride") != null && !jsonObj.get("displayNameOverride").isJsonNull()) && !jsonObj.get("displayNameOverride").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayNameOverride` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayNameOverride").toString()));
      }
      if ((jsonObj.get("descriptionOverride") != null && !jsonObj.get("descriptionOverride").isJsonNull()) && !jsonObj.get("descriptionOverride").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `descriptionOverride` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descriptionOverride").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LusidPropertyDefinitionOverrides.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LusidPropertyDefinitionOverrides' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LusidPropertyDefinitionOverrides> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LusidPropertyDefinitionOverrides.class));

       return (TypeAdapter<T>) new TypeAdapter<LusidPropertyDefinitionOverrides>() {
           @Override
           public void write(JsonWriter out, LusidPropertyDefinitionOverrides value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LusidPropertyDefinitionOverrides read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LusidPropertyDefinitionOverrides given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LusidPropertyDefinitionOverrides
  * @throws IOException if the JSON string is invalid with respect to LusidPropertyDefinitionOverrides
  */
  public static LusidPropertyDefinitionOverrides fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LusidPropertyDefinitionOverrides.class);
  }

 /**
  * Convert an instance of LusidPropertyDefinitionOverrides to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
