/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The optionality status of a property mapping for a particular vendor product entity field
 */
@JsonAdapter(Optionality.Adapter.class)
public enum Optionality {
  
  MANDATORY("Mandatory"),
  
  SUGGESTED("Suggested"),
  
  OPTIONAL("Optional");

  private String value;

  Optionality(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Optionality fromValue(String value) {
    for (Optionality b : Optionality.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Optionality> {
    @Override
    public void write(final JsonWriter jsonWriter, final Optionality enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Optionality read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Optionality.fromValue(value);
    }
  }
}

