/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.horizon.JSON;

/**
 * Request defining a post-processing task for an instance.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PostProcessTask {
  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  private String action;

  public static final String SERIALIZED_NAME_TARGET_INSTANCE = "targetInstance";
  @SerializedName(SERIALIZED_NAME_TARGET_INSTANCE)
  private String targetInstance;

  public static final String SERIALIZED_NAME_TRIGGER_ON = "triggerOn";
  @SerializedName(SERIALIZED_NAME_TRIGGER_ON)
  private String triggerOn;

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private Object parameters = null;

  public PostProcessTask() {
  }

  public PostProcessTask action(String action) {
    
    this.action = action;
    return this;
  }

   /**
   * The type of action to perform (Allowed: RunIntegration, RunWorkflow, TriggerEmail)
   * @return action
  **/
  @jakarta.annotation.Nonnull
  public String getAction() {
    return action;
  }


  public void setAction(String action) {
    this.action = action;
  }


  public PostProcessTask targetInstance(String targetInstance) {
    
    this.targetInstance = targetInstance;
    return this;
  }

   /**
   * The instance identifier to trigger (for TriggerIntegration action).
   * @return targetInstance
  **/
  @jakarta.annotation.Nullable
  public String getTargetInstance() {
    return targetInstance;
  }


  public void setTargetInstance(String targetInstance) {
    this.targetInstance = targetInstance;
  }


  public PostProcessTask triggerOn(String triggerOn) {
    
    this.triggerOn = triggerOn;
    return this;
  }

   /**
   * When the task should be triggered (Allowed: OnSuccess, OnFailure, Always)
   * @return triggerOn
  **/
  @jakarta.annotation.Nonnull
  public String getTriggerOn() {
    return triggerOn;
  }


  public void setTriggerOn(String triggerOn) {
    this.triggerOn = triggerOn;
  }


  public PostProcessTask parameters(Object parameters) {
    
    this.parameters = parameters;
    return this;
  }

   /**
   * JSON parameters specific to the action type.
   * @return parameters
  **/
  @jakarta.annotation.Nullable
  public Object getParameters() {
    return parameters;
  }


  public void setParameters(Object parameters) {
    this.parameters = parameters;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostProcessTask postProcessTask = (PostProcessTask) o;
    return Objects.equals(this.action, postProcessTask.action) &&
        Objects.equals(this.targetInstance, postProcessTask.targetInstance) &&
        Objects.equals(this.triggerOn, postProcessTask.triggerOn) &&
        Objects.equals(this.parameters, postProcessTask.parameters);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, targetInstance, triggerOn, parameters);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostProcessTask {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    targetInstance: ").append(toIndentedString(targetInstance)).append("\n");
    sb.append("    triggerOn: ").append(toIndentedString(triggerOn)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("action");
    openapiFields.add("targetInstance");
    openapiFields.add("triggerOn");
    openapiFields.add("parameters");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("action");
    openapiRequiredFields.add("triggerOn");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PostProcessTask
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostProcessTask.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostProcessTask is not found in the empty JSON string", PostProcessTask.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostProcessTask.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("action").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `action` to be a primitive type in the JSON string but got `%s`", jsonObj.get("action").toString()));
      }
      if ((jsonObj.get("targetInstance") != null && !jsonObj.get("targetInstance").isJsonNull()) && !jsonObj.get("targetInstance").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `targetInstance` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetInstance").toString()));
      }
      if (!jsonObj.get("triggerOn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `triggerOn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("triggerOn").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostProcessTask.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostProcessTask' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostProcessTask> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostProcessTask.class));

       return (TypeAdapter<T>) new TypeAdapter<PostProcessTask>() {
           @Override
           public void write(JsonWriter out, PostProcessTask value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostProcessTask read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PostProcessTask given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PostProcessTask
  * @throws IOException if the JSON string is invalid with respect to PostProcessTask
  */
  public static PostProcessTask fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostProcessTask.class);
  }

 /**
  * Convert an instance of PostProcessTask to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
