/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.horizon.JSON;

/**
 * Response from a replay transactions operation containing the CSV output.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ReplayTransactionsResponse {
  public static final String SERIALIZED_NAME_BATCH_REFERENCE_ID = "batchReferenceId";
  @SerializedName(SERIALIZED_NAME_BATCH_REFERENCE_ID)
  private String batchReferenceId;

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  private String mode;

  public static final String SERIALIZED_NAME_TRANSACTION_COUNT = "transactionCount";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_COUNT)
  private Integer transactionCount;

  public static final String SERIALIZED_NAME_CSV_OUTPUT = "csvOutput";
  @SerializedName(SERIALIZED_NAME_CSV_OUTPUT)
  private String csvOutput;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public ReplayTransactionsResponse() {
  }

  public ReplayTransactionsResponse batchReferenceId(String batchReferenceId) {
    
    this.batchReferenceId = batchReferenceId;
    return this;
  }

   /**
   * Get batchReferenceId
   * @return batchReferenceId
  **/
  @jakarta.annotation.Nonnull
  public String getBatchReferenceId() {
    return batchReferenceId;
  }


  public void setBatchReferenceId(String batchReferenceId) {
    this.batchReferenceId = batchReferenceId;
  }


  public ReplayTransactionsResponse mode(String mode) {
    
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @jakarta.annotation.Nonnull
  public String getMode() {
    return mode;
  }


  public void setMode(String mode) {
    this.mode = mode;
  }


  public ReplayTransactionsResponse transactionCount(Integer transactionCount) {
    
    this.transactionCount = transactionCount;
    return this;
  }

   /**
   * Get transactionCount
   * @return transactionCount
  **/
  @jakarta.annotation.Nonnull
  public Integer getTransactionCount() {
    return transactionCount;
  }


  public void setTransactionCount(Integer transactionCount) {
    this.transactionCount = transactionCount;
  }


  public ReplayTransactionsResponse csvOutput(String csvOutput) {
    
    this.csvOutput = csvOutput;
    return this;
  }

   /**
   * Get csvOutput
   * @return csvOutput
  **/
  @jakarta.annotation.Nonnull
  public String getCsvOutput() {
    return csvOutput;
  }


  public void setCsvOutput(String csvOutput) {
    this.csvOutput = csvOutput;
  }


  public ReplayTransactionsResponse message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @jakarta.annotation.Nonnull
  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplayTransactionsResponse replayTransactionsResponse = (ReplayTransactionsResponse) o;
    return Objects.equals(this.batchReferenceId, replayTransactionsResponse.batchReferenceId) &&
        Objects.equals(this.mode, replayTransactionsResponse.mode) &&
        Objects.equals(this.transactionCount, replayTransactionsResponse.transactionCount) &&
        Objects.equals(this.csvOutput, replayTransactionsResponse.csvOutput) &&
        Objects.equals(this.message, replayTransactionsResponse.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchReferenceId, mode, transactionCount, csvOutput, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplayTransactionsResponse {\n");
    sb.append("    batchReferenceId: ").append(toIndentedString(batchReferenceId)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    transactionCount: ").append(toIndentedString(transactionCount)).append("\n");
    sb.append("    csvOutput: ").append(toIndentedString(csvOutput)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("batchReferenceId");
    openapiFields.add("mode");
    openapiFields.add("transactionCount");
    openapiFields.add("csvOutput");
    openapiFields.add("message");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("batchReferenceId");
    openapiRequiredFields.add("mode");
    openapiRequiredFields.add("transactionCount");
    openapiRequiredFields.add("csvOutput");
    openapiRequiredFields.add("message");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ReplayTransactionsResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReplayTransactionsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReplayTransactionsResponse is not found in the empty JSON string", ReplayTransactionsResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReplayTransactionsResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("batchReferenceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `batchReferenceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("batchReferenceId").toString()));
      }
      if (!jsonObj.get("mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mode").toString()));
      }
      if (!jsonObj.get("csvOutput").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `csvOutput` to be a primitive type in the JSON string but got `%s`", jsonObj.get("csvOutput").toString()));
      }
      if (!jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReplayTransactionsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReplayTransactionsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReplayTransactionsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReplayTransactionsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ReplayTransactionsResponse>() {
           @Override
           public void write(JsonWriter out, ReplayTransactionsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReplayTransactionsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReplayTransactionsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReplayTransactionsResponse
  * @throws IOException if the JSON string is invalid with respect to ReplayTransactionsResponse
  */
  public static ReplayTransactionsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReplayTransactionsResponse.class);
  }

 /**
  * Convert an instance of ReplayTransactionsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
