/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.horizon.JSON;

/**
 * Optional parameters for replay operations.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ReplayOptions {
  public static final String SERIALIZED_NAME_OVERRIDE_PUBLICATION_STATUS = "overridePublicationStatus";
  @SerializedName(SERIALIZED_NAME_OVERRIDE_PUBLICATION_STATUS)
  private String overridePublicationStatus;

  public ReplayOptions() {
  }

  public ReplayOptions overridePublicationStatus(String overridePublicationStatus) {
    
    this.overridePublicationStatus = overridePublicationStatus;
    return this;
  }

   /**
   * Override publication status for all transactions (e.g., force as \&quot;New\&quot;).
   * @return overridePublicationStatus
  **/
  @jakarta.annotation.Nullable
  public String getOverridePublicationStatus() {
    return overridePublicationStatus;
  }


  public void setOverridePublicationStatus(String overridePublicationStatus) {
    this.overridePublicationStatus = overridePublicationStatus;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplayOptions replayOptions = (ReplayOptions) o;
    return Objects.equals(this.overridePublicationStatus, replayOptions.overridePublicationStatus);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(overridePublicationStatus);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplayOptions {\n");
    sb.append("    overridePublicationStatus: ").append(toIndentedString(overridePublicationStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("overridePublicationStatus");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ReplayOptions
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReplayOptions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReplayOptions is not found in the empty JSON string", ReplayOptions.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("overridePublicationStatus") != null && !jsonObj.get("overridePublicationStatus").isJsonNull()) && !jsonObj.get("overridePublicationStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `overridePublicationStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("overridePublicationStatus").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReplayOptions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReplayOptions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReplayOptions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReplayOptions.class));

       return (TypeAdapter<T>) new TypeAdapter<ReplayOptions>() {
           @Override
           public void write(JsonWriter out, ReplayOptions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReplayOptions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReplayOptions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReplayOptions
  * @throws IOException if the JSON string is invalid with respect to ReplayOptions
  */
  public static ReplayOptions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReplayOptions.class);
  }

 /**
  * Convert an instance of ReplayOptions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
