/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.finbourne.horizon.model.FileDestinationResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.horizon.JSON;

/**
 * record containing details of a single file for a run.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RunFileResponse {
  public static final String SERIALIZED_NAME_FILE_NAME = "fileName";
  @SerializedName(SERIALIZED_NAME_FILE_NAME)
  private String fileName;

  public static final String SERIALIZED_NAME_GENERATED_AT = "generatedAt";
  @SerializedName(SERIALIZED_NAME_GENERATED_AT)
  private OffsetDateTime generatedAt;

  public static final String SERIALIZED_NAME_ROW_COUNT = "rowCount";
  @SerializedName(SERIALIZED_NAME_ROW_COUNT)
  private Integer rowCount;

  public static final String SERIALIZED_NAME_FILE_HASH = "fileHash";
  @SerializedName(SERIALIZED_NAME_FILE_HASH)
  private String fileHash;

  public static final String SERIALIZED_NAME_ENCRYPTED = "encrypted";
  @SerializedName(SERIALIZED_NAME_ENCRYPTED)
  private Boolean encrypted;

  public static final String SERIALIZED_NAME_DESTINATIONS = "destinations";
  @SerializedName(SERIALIZED_NAME_DESTINATIONS)
  private List<FileDestinationResponse> destinations = new ArrayList<>();

  public static final String SERIALIZED_NAME_TRANSACTION_IDS = "transactionIds";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_IDS)
  private List<UUID> transactionIds = new ArrayList<>();

  public RunFileResponse() {
  }

  public RunFileResponse fileName(String fileName) {
    
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  @jakarta.annotation.Nonnull
  public String getFileName() {
    return fileName;
  }


  public void setFileName(String fileName) {
    this.fileName = fileName;
  }


  public RunFileResponse generatedAt(OffsetDateTime generatedAt) {
    
    this.generatedAt = generatedAt;
    return this;
  }

   /**
   * Get generatedAt
   * @return generatedAt
  **/
  @jakarta.annotation.Nonnull
  public OffsetDateTime getGeneratedAt() {
    return generatedAt;
  }


  public void setGeneratedAt(OffsetDateTime generatedAt) {
    this.generatedAt = generatedAt;
  }


  public RunFileResponse rowCount(Integer rowCount) {
    
    this.rowCount = rowCount;
    return this;
  }

   /**
   * Get rowCount
   * @return rowCount
  **/
  @jakarta.annotation.Nonnull
  public Integer getRowCount() {
    return rowCount;
  }


  public void setRowCount(Integer rowCount) {
    this.rowCount = rowCount;
  }


  public RunFileResponse fileHash(String fileHash) {
    
    this.fileHash = fileHash;
    return this;
  }

   /**
   * Get fileHash
   * @return fileHash
  **/
  @jakarta.annotation.Nonnull
  public String getFileHash() {
    return fileHash;
  }


  public void setFileHash(String fileHash) {
    this.fileHash = fileHash;
  }


  public RunFileResponse encrypted(Boolean encrypted) {
    
    this.encrypted = encrypted;
    return this;
  }

   /**
   * Get encrypted
   * @return encrypted
  **/
  @jakarta.annotation.Nonnull
  public Boolean getEncrypted() {
    return encrypted;
  }


  public void setEncrypted(Boolean encrypted) {
    this.encrypted = encrypted;
  }


  public RunFileResponse destinations(List<FileDestinationResponse> destinations) {
    
    this.destinations = destinations;
    return this;
  }

  public RunFileResponse addDestinationsItem(FileDestinationResponse destinationsItem) {
    if (this.destinations == null) {
      this.destinations = new ArrayList<>();
    }
    this.destinations.add(destinationsItem);
    return this;
  }

   /**
   * Get destinations
   * @return destinations
  **/
  @jakarta.annotation.Nonnull
  public List<FileDestinationResponse> getDestinations() {
    return destinations;
  }


  public void setDestinations(List<FileDestinationResponse> destinations) {
    this.destinations = destinations;
  }


  public RunFileResponse transactionIds(List<UUID> transactionIds) {
    
    this.transactionIds = transactionIds;
    return this;
  }

  public RunFileResponse addTransactionIdsItem(UUID transactionIdsItem) {
    if (this.transactionIds == null) {
      this.transactionIds = new ArrayList<>();
    }
    this.transactionIds.add(transactionIdsItem);
    return this;
  }

   /**
   * Get transactionIds
   * @return transactionIds
  **/
  @jakarta.annotation.Nonnull
  public List<UUID> getTransactionIds() {
    return transactionIds;
  }


  public void setTransactionIds(List<UUID> transactionIds) {
    this.transactionIds = transactionIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RunFileResponse runFileResponse = (RunFileResponse) o;
    return Objects.equals(this.fileName, runFileResponse.fileName) &&
        Objects.equals(this.generatedAt, runFileResponse.generatedAt) &&
        Objects.equals(this.rowCount, runFileResponse.rowCount) &&
        Objects.equals(this.fileHash, runFileResponse.fileHash) &&
        Objects.equals(this.encrypted, runFileResponse.encrypted) &&
        Objects.equals(this.destinations, runFileResponse.destinations) &&
        Objects.equals(this.transactionIds, runFileResponse.transactionIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileName, generatedAt, rowCount, fileHash, encrypted, destinations, transactionIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RunFileResponse {\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    generatedAt: ").append(toIndentedString(generatedAt)).append("\n");
    sb.append("    rowCount: ").append(toIndentedString(rowCount)).append("\n");
    sb.append("    fileHash: ").append(toIndentedString(fileHash)).append("\n");
    sb.append("    encrypted: ").append(toIndentedString(encrypted)).append("\n");
    sb.append("    destinations: ").append(toIndentedString(destinations)).append("\n");
    sb.append("    transactionIds: ").append(toIndentedString(transactionIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("fileName");
    openapiFields.add("generatedAt");
    openapiFields.add("rowCount");
    openapiFields.add("fileHash");
    openapiFields.add("encrypted");
    openapiFields.add("destinations");
    openapiFields.add("transactionIds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("fileName");
    openapiRequiredFields.add("generatedAt");
    openapiRequiredFields.add("rowCount");
    openapiRequiredFields.add("fileHash");
    openapiRequiredFields.add("encrypted");
    openapiRequiredFields.add("destinations");
    openapiRequiredFields.add("transactionIds");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to RunFileResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RunFileResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RunFileResponse is not found in the empty JSON string", RunFileResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RunFileResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("fileName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fileName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileName").toString()));
      }
      if (!jsonObj.get("fileHash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fileHash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileHash").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("destinations").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `destinations` to be an array in the JSON string but got `%s`", jsonObj.get("destinations").toString()));
      }

      JsonArray jsonArraydestinations = jsonObj.getAsJsonArray("destinations");
      // validate the required field `destinations` (array)
      for (int i = 0; i < jsonArraydestinations.size(); i++) {
        FileDestinationResponse.validateJsonElement(jsonArraydestinations.get(i));
      };
      // ensure the required json array is present
      if (jsonObj.get("transactionIds") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("transactionIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `transactionIds` to be an array in the JSON string but got `%s`", jsonObj.get("transactionIds").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RunFileResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RunFileResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RunFileResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RunFileResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<RunFileResponse>() {
           @Override
           public void write(JsonWriter out, RunFileResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RunFileResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RunFileResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RunFileResponse
  * @throws IOException if the JSON string is invalid with respect to RunFileResponse
  */
  public static RunFileResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RunFileResponse.class);
  }

 /**
  * Convert an instance of RunFileResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
