/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.horizon.JSON;

/**
 * Information about a file delivery
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TpfFileDeliveryInfo {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_FILE_NAME = "fileName";
  @SerializedName(SERIALIZED_NAME_FILE_NAME)
  private String fileName;

  public static final String SERIALIZED_NAME_FILE_HASH = "fileHash";
  @SerializedName(SERIALIZED_NAME_FILE_HASH)
  private String fileHash;

  public static final String SERIALIZED_NAME_DESTINATION_PATH = "destinationPath";
  @SerializedName(SERIALIZED_NAME_DESTINATION_PATH)
  private String destinationPath;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_GENERATED_AT = "generatedAt";
  @SerializedName(SERIALIZED_NAME_GENERATED_AT)
  private OffsetDateTime generatedAt;

  public TpfFileDeliveryInfo() {
  }

  public TpfFileDeliveryInfo id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * File delivery ID
   * @return id
  **/
  @jakarta.annotation.Nonnull
  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public TpfFileDeliveryInfo fileName(String fileName) {
    
    this.fileName = fileName;
    return this;
  }

   /**
   * File name
   * @return fileName
  **/
  @jakarta.annotation.Nonnull
  public String getFileName() {
    return fileName;
  }


  public void setFileName(String fileName) {
    this.fileName = fileName;
  }


  public TpfFileDeliveryInfo fileHash(String fileHash) {
    
    this.fileHash = fileHash;
    return this;
  }

   /**
   * SHA-256 hash of the file content
   * @return fileHash
  **/
  @jakarta.annotation.Nonnull
  public String getFileHash() {
    return fileHash;
  }


  public void setFileHash(String fileHash) {
    this.fileHash = fileHash;
  }


  public TpfFileDeliveryInfo destinationPath(String destinationPath) {
    
    this.destinationPath = destinationPath;
    return this;
  }

   /**
   * SFTP destination path
   * @return destinationPath
  **/
  @jakarta.annotation.Nonnull
  public String getDestinationPath() {
    return destinationPath;
  }


  public void setDestinationPath(String destinationPath) {
    this.destinationPath = destinationPath;
  }


  public TpfFileDeliveryInfo status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Delivery status
   * @return status
  **/
  @jakarta.annotation.Nonnull
  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public TpfFileDeliveryInfo generatedAt(OffsetDateTime generatedAt) {
    
    this.generatedAt = generatedAt;
    return this;
  }

   /**
   * Timestamp when the file was originally generated
   * @return generatedAt
  **/
  @jakarta.annotation.Nonnull
  public OffsetDateTime getGeneratedAt() {
    return generatedAt;
  }


  public void setGeneratedAt(OffsetDateTime generatedAt) {
    this.generatedAt = generatedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpfFileDeliveryInfo tpfFileDeliveryInfo = (TpfFileDeliveryInfo) o;
    return Objects.equals(this.id, tpfFileDeliveryInfo.id) &&
        Objects.equals(this.fileName, tpfFileDeliveryInfo.fileName) &&
        Objects.equals(this.fileHash, tpfFileDeliveryInfo.fileHash) &&
        Objects.equals(this.destinationPath, tpfFileDeliveryInfo.destinationPath) &&
        Objects.equals(this.status, tpfFileDeliveryInfo.status) &&
        Objects.equals(this.generatedAt, tpfFileDeliveryInfo.generatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, fileName, fileHash, destinationPath, status, generatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpfFileDeliveryInfo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    fileHash: ").append(toIndentedString(fileHash)).append("\n");
    sb.append("    destinationPath: ").append(toIndentedString(destinationPath)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    generatedAt: ").append(toIndentedString(generatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("fileName");
    openapiFields.add("fileHash");
    openapiFields.add("destinationPath");
    openapiFields.add("status");
    openapiFields.add("generatedAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("fileName");
    openapiRequiredFields.add("fileHash");
    openapiRequiredFields.add("destinationPath");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("generatedAt");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TpfFileDeliveryInfo
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TpfFileDeliveryInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TpfFileDeliveryInfo is not found in the empty JSON string", TpfFileDeliveryInfo.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TpfFileDeliveryInfo.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("fileName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fileName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileName").toString()));
      }
      if (!jsonObj.get("fileHash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fileHash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileHash").toString()));
      }
      if (!jsonObj.get("destinationPath").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destinationPath` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinationPath").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TpfFileDeliveryInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TpfFileDeliveryInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TpfFileDeliveryInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TpfFileDeliveryInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<TpfFileDeliveryInfo>() {
           @Override
           public void write(JsonWriter out, TpfFileDeliveryInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TpfFileDeliveryInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TpfFileDeliveryInfo given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TpfFileDeliveryInfo
  * @throws IOException if the JSON string is invalid with respect to TpfFileDeliveryInfo
  */
  public static TpfFileDeliveryInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TpfFileDeliveryInfo.class);
  }

 /**
  * Convert an instance of TpfFileDeliveryInfo to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
