/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.horizon.JSON;

/**
 * Response model for TPF file delivery search results
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TpfFileDeliveryResponse {
  public static final String SERIALIZED_NAME_RUN_ID = "runId";
  @SerializedName(SERIALIZED_NAME_RUN_ID)
  private String runId;

  public static final String SERIALIZED_NAME_RUN_START_TIME = "runStartTime";
  @SerializedName(SERIALIZED_NAME_RUN_START_TIME)
  private OffsetDateTime runStartTime;

  public static final String SERIALIZED_NAME_FILE_NAME = "fileName";
  @SerializedName(SERIALIZED_NAME_FILE_NAME)
  private String fileName;

  public static final String SERIALIZED_NAME_GENERATED_AT = "generatedAt";
  @SerializedName(SERIALIZED_NAME_GENERATED_AT)
  private OffsetDateTime generatedAt;

  public static final String SERIALIZED_NAME_ROW_COUNT = "rowCount";
  @SerializedName(SERIALIZED_NAME_ROW_COUNT)
  private Integer rowCount;

  public static final String SERIALIZED_NAME_FILE_HASH = "fileHash";
  @SerializedName(SERIALIZED_NAME_FILE_HASH)
  private String fileHash;

  public static final String SERIALIZED_NAME_DESTINATION_TYPE = "destinationType";
  @SerializedName(SERIALIZED_NAME_DESTINATION_TYPE)
  private String destinationType;

  public static final String SERIALIZED_NAME_DESTINATION_PATH = "destinationPath";
  @SerializedName(SERIALIZED_NAME_DESTINATION_PATH)
  private String destinationPath;

  public static final String SERIALIZED_NAME_DESTINATION_STATUS = "destinationStatus";
  @SerializedName(SERIALIZED_NAME_DESTINATION_STATUS)
  private String destinationStatus;

  public static final String SERIALIZED_NAME_DESTINATION_ERROR = "destinationError";
  @SerializedName(SERIALIZED_NAME_DESTINATION_ERROR)
  private String destinationError;

  public static final String SERIALIZED_NAME_DESTINATION_NAME = "destinationName";
  @SerializedName(SERIALIZED_NAME_DESTINATION_NAME)
  private String destinationName;

  public TpfFileDeliveryResponse() {
  }

  public TpfFileDeliveryResponse runId(String runId) {
    
    this.runId = runId;
    return this;
  }

   /**
   * Get runId
   * @return runId
  **/
  @jakarta.annotation.Nullable
  public String getRunId() {
    return runId;
  }


  public void setRunId(String runId) {
    this.runId = runId;
  }


  public TpfFileDeliveryResponse runStartTime(OffsetDateTime runStartTime) {
    
    this.runStartTime = runStartTime;
    return this;
  }

   /**
   * Get runStartTime
   * @return runStartTime
  **/
  @jakarta.annotation.Nullable
  public OffsetDateTime getRunStartTime() {
    return runStartTime;
  }


  public void setRunStartTime(OffsetDateTime runStartTime) {
    this.runStartTime = runStartTime;
  }


  public TpfFileDeliveryResponse fileName(String fileName) {
    
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  @jakarta.annotation.Nonnull
  public String getFileName() {
    return fileName;
  }


  public void setFileName(String fileName) {
    this.fileName = fileName;
  }


  public TpfFileDeliveryResponse generatedAt(OffsetDateTime generatedAt) {
    
    this.generatedAt = generatedAt;
    return this;
  }

   /**
   * Get generatedAt
   * @return generatedAt
  **/
  @jakarta.annotation.Nonnull
  public OffsetDateTime getGeneratedAt() {
    return generatedAt;
  }


  public void setGeneratedAt(OffsetDateTime generatedAt) {
    this.generatedAt = generatedAt;
  }


  public TpfFileDeliveryResponse rowCount(Integer rowCount) {
    
    this.rowCount = rowCount;
    return this;
  }

   /**
   * Get rowCount
   * @return rowCount
  **/
  @jakarta.annotation.Nonnull
  public Integer getRowCount() {
    return rowCount;
  }


  public void setRowCount(Integer rowCount) {
    this.rowCount = rowCount;
  }


  public TpfFileDeliveryResponse fileHash(String fileHash) {
    
    this.fileHash = fileHash;
    return this;
  }

   /**
   * Get fileHash
   * @return fileHash
  **/
  @jakarta.annotation.Nullable
  public String getFileHash() {
    return fileHash;
  }


  public void setFileHash(String fileHash) {
    this.fileHash = fileHash;
  }


  public TpfFileDeliveryResponse destinationType(String destinationType) {
    
    this.destinationType = destinationType;
    return this;
  }

   /**
   * Get destinationType
   * @return destinationType
  **/
  @jakarta.annotation.Nonnull
  public String getDestinationType() {
    return destinationType;
  }


  public void setDestinationType(String destinationType) {
    this.destinationType = destinationType;
  }


  public TpfFileDeliveryResponse destinationPath(String destinationPath) {
    
    this.destinationPath = destinationPath;
    return this;
  }

   /**
   * Get destinationPath
   * @return destinationPath
  **/
  @jakarta.annotation.Nullable
  public String getDestinationPath() {
    return destinationPath;
  }


  public void setDestinationPath(String destinationPath) {
    this.destinationPath = destinationPath;
  }


  public TpfFileDeliveryResponse destinationStatus(String destinationStatus) {
    
    this.destinationStatus = destinationStatus;
    return this;
  }

   /**
   * Get destinationStatus
   * @return destinationStatus
  **/
  @jakarta.annotation.Nonnull
  public String getDestinationStatus() {
    return destinationStatus;
  }


  public void setDestinationStatus(String destinationStatus) {
    this.destinationStatus = destinationStatus;
  }


  public TpfFileDeliveryResponse destinationError(String destinationError) {
    
    this.destinationError = destinationError;
    return this;
  }

   /**
   * Get destinationError
   * @return destinationError
  **/
  @jakarta.annotation.Nullable
  public String getDestinationError() {
    return destinationError;
  }


  public void setDestinationError(String destinationError) {
    this.destinationError = destinationError;
  }


  public TpfFileDeliveryResponse destinationName(String destinationName) {
    
    this.destinationName = destinationName;
    return this;
  }

   /**
   * Get destinationName
   * @return destinationName
  **/
  @jakarta.annotation.Nullable
  public String getDestinationName() {
    return destinationName;
  }


  public void setDestinationName(String destinationName) {
    this.destinationName = destinationName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpfFileDeliveryResponse tpfFileDeliveryResponse = (TpfFileDeliveryResponse) o;
    return Objects.equals(this.runId, tpfFileDeliveryResponse.runId) &&
        Objects.equals(this.runStartTime, tpfFileDeliveryResponse.runStartTime) &&
        Objects.equals(this.fileName, tpfFileDeliveryResponse.fileName) &&
        Objects.equals(this.generatedAt, tpfFileDeliveryResponse.generatedAt) &&
        Objects.equals(this.rowCount, tpfFileDeliveryResponse.rowCount) &&
        Objects.equals(this.fileHash, tpfFileDeliveryResponse.fileHash) &&
        Objects.equals(this.destinationType, tpfFileDeliveryResponse.destinationType) &&
        Objects.equals(this.destinationPath, tpfFileDeliveryResponse.destinationPath) &&
        Objects.equals(this.destinationStatus, tpfFileDeliveryResponse.destinationStatus) &&
        Objects.equals(this.destinationError, tpfFileDeliveryResponse.destinationError) &&
        Objects.equals(this.destinationName, tpfFileDeliveryResponse.destinationName);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(runId, runStartTime, fileName, generatedAt, rowCount, fileHash, destinationType, destinationPath, destinationStatus, destinationError, destinationName);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpfFileDeliveryResponse {\n");
    sb.append("    runId: ").append(toIndentedString(runId)).append("\n");
    sb.append("    runStartTime: ").append(toIndentedString(runStartTime)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    generatedAt: ").append(toIndentedString(generatedAt)).append("\n");
    sb.append("    rowCount: ").append(toIndentedString(rowCount)).append("\n");
    sb.append("    fileHash: ").append(toIndentedString(fileHash)).append("\n");
    sb.append("    destinationType: ").append(toIndentedString(destinationType)).append("\n");
    sb.append("    destinationPath: ").append(toIndentedString(destinationPath)).append("\n");
    sb.append("    destinationStatus: ").append(toIndentedString(destinationStatus)).append("\n");
    sb.append("    destinationError: ").append(toIndentedString(destinationError)).append("\n");
    sb.append("    destinationName: ").append(toIndentedString(destinationName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("runId");
    openapiFields.add("runStartTime");
    openapiFields.add("fileName");
    openapiFields.add("generatedAt");
    openapiFields.add("rowCount");
    openapiFields.add("fileHash");
    openapiFields.add("destinationType");
    openapiFields.add("destinationPath");
    openapiFields.add("destinationStatus");
    openapiFields.add("destinationError");
    openapiFields.add("destinationName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("fileName");
    openapiRequiredFields.add("generatedAt");
    openapiRequiredFields.add("rowCount");
    openapiRequiredFields.add("destinationType");
    openapiRequiredFields.add("destinationStatus");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TpfFileDeliveryResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TpfFileDeliveryResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TpfFileDeliveryResponse is not found in the empty JSON string", TpfFileDeliveryResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TpfFileDeliveryResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("runId") != null && !jsonObj.get("runId").isJsonNull()) && !jsonObj.get("runId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `runId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("runId").toString()));
      }
      if (!jsonObj.get("fileName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fileName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileName").toString()));
      }
      if ((jsonObj.get("fileHash") != null && !jsonObj.get("fileHash").isJsonNull()) && !jsonObj.get("fileHash").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fileHash` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileHash").toString()));
      }
      if (!jsonObj.get("destinationType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destinationType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinationType").toString()));
      }
      if ((jsonObj.get("destinationPath") != null && !jsonObj.get("destinationPath").isJsonNull()) && !jsonObj.get("destinationPath").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destinationPath` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinationPath").toString()));
      }
      if (!jsonObj.get("destinationStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destinationStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinationStatus").toString()));
      }
      if ((jsonObj.get("destinationError") != null && !jsonObj.get("destinationError").isJsonNull()) && !jsonObj.get("destinationError").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destinationError` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinationError").toString()));
      }
      if ((jsonObj.get("destinationName") != null && !jsonObj.get("destinationName").isJsonNull()) && !jsonObj.get("destinationName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `destinationName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinationName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TpfFileDeliveryResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TpfFileDeliveryResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TpfFileDeliveryResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TpfFileDeliveryResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<TpfFileDeliveryResponse>() {
           @Override
           public void write(JsonWriter out, TpfFileDeliveryResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TpfFileDeliveryResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TpfFileDeliveryResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TpfFileDeliveryResponse
  * @throws IOException if the JSON string is invalid with respect to TpfFileDeliveryResponse
  */
  public static TpfFileDeliveryResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TpfFileDeliveryResponse.class);
  }

 /**
  * Convert an instance of TpfFileDeliveryResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
