/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.horizon.JSON;

/**
 * Result for a single batch element retry attempt
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TpfRetryElementResult {
  public static final String SERIALIZED_NAME_BATCH_ELEMENT_REFERENCE_ID = "batchElementReferenceId";
  @SerializedName(SERIALIZED_NAME_BATCH_ELEMENT_REFERENCE_ID)
  private String batchElementReferenceId;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public TpfRetryElementResult() {
  }

  public TpfRetryElementResult batchElementReferenceId(String batchElementReferenceId) {
    
    this.batchElementReferenceId = batchElementReferenceId;
    return this;
  }

   /**
   * Batch element reference identifier
   * @return batchElementReferenceId
  **/
  @jakarta.annotation.Nonnull
  public String getBatchElementReferenceId() {
    return batchElementReferenceId;
  }


  public void setBatchElementReferenceId(String batchElementReferenceId) {
    this.batchElementReferenceId = batchElementReferenceId;
  }


  public TpfRetryElementResult status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status of the retry attempt (e.g., \&quot;Retrying\&quot;, \&quot;NotFound\&quot;)
   * @return status
  **/
  @jakarta.annotation.Nonnull
  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TpfRetryElementResult tpfRetryElementResult = (TpfRetryElementResult) o;
    return Objects.equals(this.batchElementReferenceId, tpfRetryElementResult.batchElementReferenceId) &&
        Objects.equals(this.status, tpfRetryElementResult.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(batchElementReferenceId, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TpfRetryElementResult {\n");
    sb.append("    batchElementReferenceId: ").append(toIndentedString(batchElementReferenceId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("batchElementReferenceId");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("batchElementReferenceId");
    openapiRequiredFields.add("status");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TpfRetryElementResult
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TpfRetryElementResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TpfRetryElementResult is not found in the empty JSON string", TpfRetryElementResult.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TpfRetryElementResult.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("batchElementReferenceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `batchElementReferenceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("batchElementReferenceId").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TpfRetryElementResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TpfRetryElementResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TpfRetryElementResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TpfRetryElementResult.class));

       return (TypeAdapter<T>) new TypeAdapter<TpfRetryElementResult>() {
           @Override
           public void write(JsonWriter out, TpfRetryElementResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TpfRetryElementResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TpfRetryElementResult given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TpfRetryElementResult
  * @throws IOException if the JSON string is invalid with respect to TpfRetryElementResult
  */
  public static TpfRetryElementResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TpfRetryElementResult.class);
  }

 /**
  * Convert an instance of TpfRetryElementResult to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
