/*
 * FINBOURNE Horizon API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.horizon.model;

import java.util.Objects;
import com.finbourne.horizon.model.WorkflowResultFieldResponse;
import com.finbourne.horizon.model.WorkflowResultFieldsTaskResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.horizon.JSON;

/**
 * The result fields an instance returns to the Workflow task that started its run.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WorkflowResultFieldsResponse {
  public static final String SERIALIZED_NAME_INSTANCE_ID = "instanceId";
  @SerializedName(SERIALIZED_NAME_INSTANCE_ID)
  private String instanceId;

  public static final String SERIALIZED_NAME_REPORTS_TO_WORKFLOW = "reportsToWorkflow";
  @SerializedName(SERIALIZED_NAME_REPORTS_TO_WORKFLOW)
  private Boolean reportsToWorkflow;

  public static final String SERIALIZED_NAME_RESULT_FIELDS = "resultFields";
  @SerializedName(SERIALIZED_NAME_RESULT_FIELDS)
  private List<WorkflowResultFieldResponse> resultFields = new ArrayList<>();

  public static final String SERIALIZED_NAME_TASKS = "tasks";
  @SerializedName(SERIALIZED_NAME_TASKS)
  private List<WorkflowResultFieldsTaskResponse> tasks = new ArrayList<>();

  public WorkflowResultFieldsResponse() {
  }

  public WorkflowResultFieldsResponse instanceId(String instanceId) {
    
    this.instanceId = instanceId;
    return this;
  }

   /**
   * The instance these fields belong to.
   * @return instanceId
  **/
  @jakarta.annotation.Nonnull
  public String getInstanceId() {
    return instanceId;
  }


  public void setInstanceId(String instanceId) {
    this.instanceId = instanceId;
  }


  public WorkflowResultFieldsResponse reportsToWorkflow(Boolean reportsToWorkflow) {
    
    this.reportsToWorkflow = reportsToWorkflow;
    return this;
  }

   /**
   * Whether this instance has an enabled RunWorkflow post-process task at all.
   * @return reportsToWorkflow
  **/
  @jakarta.annotation.Nonnull
  public Boolean getReportsToWorkflow() {
    return reportsToWorkflow;
  }


  public void setReportsToWorkflow(Boolean reportsToWorkflow) {
    this.reportsToWorkflow = reportsToWorkflow;
  }


  public WorkflowResultFieldsResponse resultFields(List<WorkflowResultFieldResponse> resultFields) {
    
    this.resultFields = resultFields;
    return this;
  }

  public WorkflowResultFieldsResponse addResultFieldsItem(WorkflowResultFieldResponse resultFieldsItem) {
    if (this.resultFields == null) {
      this.resultFields = new ArrayList<>();
    }
    this.resultFields.add(resultFieldsItem);
    return this;
  }

   /**
   * Every distinct field declared across this instance&#39;s RunWorkflow tasks.
   * @return resultFields
  **/
  @jakarta.annotation.Nonnull
  public List<WorkflowResultFieldResponse> getResultFields() {
    return resultFields;
  }


  public void setResultFields(List<WorkflowResultFieldResponse> resultFields) {
    this.resultFields = resultFields;
  }


  public WorkflowResultFieldsResponse tasks(List<WorkflowResultFieldsTaskResponse> tasks) {
    
    this.tasks = tasks;
    return this;
  }

  public WorkflowResultFieldsResponse addTasksItem(WorkflowResultFieldsTaskResponse tasksItem) {
    if (this.tasks == null) {
      this.tasks = new ArrayList<>();
    }
    this.tasks.add(tasksItem);
    return this;
  }

   /**
   * Per-task breakdown: an instance may declare different fields on success and on failure.
   * @return tasks
  **/
  @jakarta.annotation.Nonnull
  public List<WorkflowResultFieldsTaskResponse> getTasks() {
    return tasks;
  }


  public void setTasks(List<WorkflowResultFieldsTaskResponse> tasks) {
    this.tasks = tasks;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowResultFieldsResponse workflowResultFieldsResponse = (WorkflowResultFieldsResponse) o;
    return Objects.equals(this.instanceId, workflowResultFieldsResponse.instanceId) &&
        Objects.equals(this.reportsToWorkflow, workflowResultFieldsResponse.reportsToWorkflow) &&
        Objects.equals(this.resultFields, workflowResultFieldsResponse.resultFields) &&
        Objects.equals(this.tasks, workflowResultFieldsResponse.tasks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instanceId, reportsToWorkflow, resultFields, tasks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowResultFieldsResponse {\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    reportsToWorkflow: ").append(toIndentedString(reportsToWorkflow)).append("\n");
    sb.append("    resultFields: ").append(toIndentedString(resultFields)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("instanceId");
    openapiFields.add("reportsToWorkflow");
    openapiFields.add("resultFields");
    openapiFields.add("tasks");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("instanceId");
    openapiRequiredFields.add("reportsToWorkflow");
    openapiRequiredFields.add("resultFields");
    openapiRequiredFields.add("tasks");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to WorkflowResultFieldsResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WorkflowResultFieldsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WorkflowResultFieldsResponse is not found in the empty JSON string", WorkflowResultFieldsResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WorkflowResultFieldsResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("instanceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `instanceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("instanceId").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("resultFields").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `resultFields` to be an array in the JSON string but got `%s`", jsonObj.get("resultFields").toString()));
      }

      JsonArray jsonArrayresultFields = jsonObj.getAsJsonArray("resultFields");
      // validate the required field `resultFields` (array)
      for (int i = 0; i < jsonArrayresultFields.size(); i++) {
        WorkflowResultFieldResponse.validateJsonElement(jsonArrayresultFields.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("tasks").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tasks` to be an array in the JSON string but got `%s`", jsonObj.get("tasks").toString()));
      }

      JsonArray jsonArraytasks = jsonObj.getAsJsonArray("tasks");
      // validate the required field `tasks` (array)
      for (int i = 0; i < jsonArraytasks.size(); i++) {
        WorkflowResultFieldsTaskResponse.validateJsonElement(jsonArraytasks.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WorkflowResultFieldsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WorkflowResultFieldsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WorkflowResultFieldsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WorkflowResultFieldsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<WorkflowResultFieldsResponse>() {
           @Override
           public void write(JsonWriter out, WorkflowResultFieldsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WorkflowResultFieldsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WorkflowResultFieldsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WorkflowResultFieldsResponse
  * @throws IOException if the JSON string is invalid with respect to WorkflowResultFieldsResponse
  */
  public static WorkflowResultFieldsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WorkflowResultFieldsResponse.class);
  }

 /**
  * Convert an instance of WorkflowResultFieldsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
